spring.application.name=Funkos

spring.datasource.url=jdbc:h2:mem:funkodb
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.h2.Driver

# create-drop para desarrollo, en update para produccion.
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect